# Generated by Django 3.2.9 on 2021-11-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deck_type',
            field=models.CharField(null=True, default=None, max_length=20),
        ),
    ]
